"""File storing

Revision ID: 6be4ac827efd
Revises: 4773b983fd97
Create Date: 2023-04-27 06:22:16.483657

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6be4ac827efd'
down_revision = '4773b983fd97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file', postgresql.BYTEA(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'file')
    # ### end Alembic commands ###
